### PR TITLE
OPENEUROPA-719: Latest version of GrumPHP causes errors

### PR DESCRIPTION
**Pull request by pfrenssen**
The version range on GrumPhp is too strict, forcing it to remain on an old version of more than a year ago. This is due to the difference in handling packages that are still in version 0: using `^0.11` will prevent it from going up minor versions, while `~0.11` will allow it. Only packages that have a version 1 or higher are allowed to advance minor versions when using `^`.

Ref. https://getcomposer.org/doc/articles/versions.md#caret-version-range-

### CODE REVIEW

**Comment by pfrenssen** [comment]
Hold a second with merging, the build is failing. We need to see what is wrong here.

**Comment by ademarco** [comment]
I've locked merging if build is failing, it was indeed missing on this specific project.

**Comment by pfrenssen** [comment]
Let's start the adventure by putting quotes around the reserved keywords like the dependency injection container demands.

**Comment by pfrenssen** [comment]
Oopsie!

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "task.phpmd" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

The Symfony 4 container not only got stricter in the use of quotes for service parameters, but they also no longer allow to directly retrieve services from the container unless they are marked as `public`.

We are doing this in our tests:

```
$task = $container->get('task.phpmd'); // No longer allowed!
```

Symfony suggests to either make the services public, or use dependency injection. We have neither option. The tasks are owned by GrumPHP and not by us, so we cannot make them public (it would be a bad idea anyway). Also we cannot inject them since we are using them in a test, not in a service. So we need a third option: a factory. Luckily GrumPHP has a factory for tasks built into their TaskRunner class and allows us to access them through `$taskrunner->getTasks()`.

**Comment by pfrenssen** [comment]
It starts to look a bit better now, most tests are green, but we have two mysterious failures:

```
OpenEuropa\CodeReview\Test\GitCommitMessageTest::testCommitMessage with data set #0 ('Issue #3: Nice GitHub commit message.', 0)
Failed asserting that 0 matches expected 99.
```

The first thing that is apparent is that the data set expects the value "0", but the test results says that it "failed the expected 99". This is a simple typo, when we are asserting we should put the expected value as the first argument. The tests are doing this:

```
$this->assertEquals($result->getResultCode(), $expected);
```

But should be doing this:

```
$this->assertEquals($expected, $result->getResultCode());
```

And then there is the reason why this test is failing. It appears that in the latest version of GrumPHP a new `enforce_no_subject_trailing_period` option was added to the commit message checker and this is enabled by default. This conflicts with our own regex which expects a period at the end. We need to update our configuration to allow trailing periods.

**Comment by pfrenssen** [comment]
Yay the test is green!

But our story isn't over yet, we first need to refactor a bit since we added quite a bit of duplicated code in the tests. This is the piece of code that is duplicated:

```
    protected function getTask($name)
    {
        $container = $this->getContainer($this->getDistPath().'/drupal-conventions.yml');
        /** @var \GrumPHP\Runner\TaskRunner $taskrunner */
        $taskrunner = $container->get('task_runner');
        foreach ($taskrunner->getTasks() as $task) {
            if ($task->getName() === $name) {
                return $task;
            }
        }

        throw new \InvalidArgumentException("Task with name $name is not registered.");
    }
```

It is duplicated because the first line that retrieves the container has the path to the conventions file hard coded in it. This is different for each test.

We can solve this easily by putting the name of the convention to test in a property on the test class:

```
protected $convention = 'drupal-conventions';
```

If we then use this data to construct the right path to the YAML file, and create the service based on that, we no longer need to hardcode the filename, and we can deduplicate the code.

Let's also clean up the documentation a bit while we're at it.

**Comment by pfrenssen** [comment]
The tests for our "highest" dependency versions are OK, but the "lowest" ones are failing! Uh oh!

It seems we have multiple problems:

```
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /test/code-review/test/AbstractTest.php on line 14
```

Since we are using the namespaced version of this class which was introduced in PHPUnit 6 our test suite is in fact not compatible with PHPUnit 5 any more.

```
/test/code-review/test/fixtures/phpmd/incorrect-code.php:4	The method example() has a Cyclomatic Complexity of 11. The configured cyclomatic complexity threshold is 10.
```

PHPMD is testing the `incorrect-code.php` file even though it is blacklisted. This is a bug that is fixed in more recent versions of PHPMD. I looked through the commit history but I couldn't find the exact commit that fixed it.

```
PHP Warning:  Use of undefined constant T_BAD_CHARACTER - assumed 'T_BAD_CHARACTER' (this will throw an Error in a future version of PHP) in /home/pieter/v/code-review/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php on line 548
```

This is a bug in the PDepend library which is a dependency of PHPMD. The fixed version is included in PHPMD 2.6.0, so we should use this as our minimum version.

**Comment by pfrenssen** [comment]
Running the tests with our updated minimum requirements unearths a final problem: now that the tests for GrumPHP can be run successfully we are getting another error:

```
Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "enforce_no_subject_trailing_period" does not exist. 
```

A few steps back we had to define this option which was introduced in GrumPHP 0.12.0, but now when we use version 0.11.0 it doesn't know what to do with it. So the minimum version should be bumped to 0.12.

**Comment by pfrenssen** [comment]
Yay green! We can now be reasonably certain that the full version range we specify is actually working.

One final step is to fix the merge conflict with the master branch.

**Pull request merged**
